# Generated by Django 5.2.8 on 2025-12-03 13:32

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя пользователя", verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия пользователя",
                        verbose_name="Фамилия пользователя",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Номер телефона пользователя",
                        verbose_name="Номер телефона пользователя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email пользователя",
                        max_length=254,
                        unique=True,
                        verbose_name="Email пользователя",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Обычный пользователь"), ("admin", "Админ")],
                        default="user",
                        help_text="Роль пользователя",
                        verbose_name="Роль пользователя",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/user.png",
                        help_text="Аватарка пользователя",
                        upload_to="",
                        verbose_name="Аватарка пользователя",
                    ),
                ),
                (
                    "mailing",
                    models.BooleanField(
                        default=False,
                        help_text="Статус рассылки о количестве новых отзывов под объявлениями пользователя",
                        verbose_name="Статус рассылки о количестве новых отзывов под объявлениями пользователя",
                    ),
                ),
                (
                    "mailing_frequency",
                    models.CharField(
                        choices=[
                            ("day", "Ежедневная рассылка"),
                            ("week", "Еженедельная рассылка"),
                            ("month", "Ежемесячная рассылка"),
                        ],
                        default="month",
                        help_text="Частота рассылки: день/неделя/месяц (Если рассылка активна | mailing=True)",
                        verbose_name="Частота рассылки: день/неделя/месяц (Если рассылка активна | mailing=True)",
                    ),
                ),
                (
                    "next_mailing",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата следующей рассылки (Если рассылка активна | mailing=True)",
                        verbose_name="Дата следующей рассылки (Если рассылка активна | mailing=True)",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователь",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
