# Generated by Django 5.2.8 on 2025-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="next_mailing",
            field=models.DateField(
                blank=True,
                help_text="Дата следующей рассылки (Если рассылка активна | mailing=True)",
                null=True,
                verbose_name="Дата следующей рассылки (Если рассылка активна | mailing=True)",
            ),
        ),
    ]
