# Generated by Django 5.2.8 on 2025-11-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="reported_by_mail",
            field=models.BooleanField(
                default=False,
                help_text="Статус осведомленности пользователя о новом отзыве под его объявлением",
                verbose_name="Статус осведомленности пользователя о новом отзыве под его объявлением",
            ),
        ),
    ]
