# Generated by Django 5.2.8 on 2025-12-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("board", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Автор объявления",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор объявления",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Автор отзыва",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор отзыва",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="related_ad",
            field=models.ForeignKey(
                help_text="Объявление, под которым оставлен отзыв",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="board.ad",
                verbose_name="Объявление, под которым оставлен отзыв",
            ),
        ),
    ]
