# Generated by Django 5.2.8 on 2025-11-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="related_ad",
            field=models.ForeignKey(
                help_text="Объявление, под которым оставлен отзыв",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="board.ad",
                verbose_name="Объявление, под которым оставлен отзыв",
            ),
        ),
    ]
